// Generated by scripts/generate-pwa-icons.mjs from scripts/brand/flux-mark.mjs. Do not edit.

/** One ribbon on the 24 grid; the other three are it turned by 90°, 180°, 270° about (12, 12). */
export const RIBBON_PATH = "M15.2 8.8V18.8A3.6 3.6 0 1 0 18.8 15.2H15.2";
export const STROKE_WIDTH = 2.5;
/** The square the mark fills on the 24 grid, stroke included: the drawing's viewBox. */
export const MARK_BOX = { lo: 0.35, size: 23.3 };
/** The ribbons' tones on the navy, in the order they are drawn. */
export const TONES = ["#5fd6ff", "#4b86ff", "#6b6bff", "#a07cff"] as const;
/** The launch screen's colour: the manifest's background_color and the iOS launch images. */
export const LAUNCH_BG = "#15224d";
