// Tenant-only schema: everything except platform registry tables (tenants, tenantMembers).
// Used by migrateTenantDb() so that platform tables are never pushed to tenant databases.
export {
  accounts,
  activities,
  activitiesRelations,
  appointmentAttendees,
  appointmentAttendeesRelations,
  // Appointments
  appointments,
  appointmentsRelations,
  automationLogs,
  automationLogsRelations,
  // Automation
  automationRules,
  automationRulesRelations,
  businessCalendar,
  businessHolidays,
  campaignLogs,
  campaignLogsRelations,
  // Chat / DM
  // CRM core
  companies,
  contacts,
  contactsRelations,
  // Custom fields
  customFieldDefinitions,
  customFieldDefinitionsRelations,
  customFieldValues,
  customFieldValuesRelations,
  // Filters
  customFilters,
  customFiltersRelations,
  customFilterTags,
  customFilterTagsRelations,
  dealComments,
  dealCommentsRelations,
  dealLossReasons,
  deals,
  dealsRelations,
  dmConversationMembers,
  dmConversationMembersRelations,
  dmConversations,
  dmConversationsRelations,
  dmMessages,
  dmMessagesRelations,
  // Documents
  documents,
  emailJobs,
  emailSettings,
  emailSuppressions,
  // Marketing / email
  emailTemplates,
  emailTemplatesRelations,
  // Exchange rates cache
  exchangeRatesCache,
  filterPresets,
  geoCities,
  // Geo reference
  geoCountries,
  leads,
  leadsRelations,
  marketingCampaigns,
  marketingCampaignsRelations,
  // Notifications
  notifications,
  notificationsRelations,
  orderItems,
  orders,
  passwordResetTokens,
  // Pipeline / deals
  pipelineStages,
  pipelineStagesRelations,
  // Products / orders / quotes
  products,
  quoteActivities,
  quoteActivitiesRelations,
  quoteItems,
  quoteItemsRelations,
  quotes,
  quotesRelations,
  // Finance
  salesTargets,
  salesTargetsRelations,
  // Reports
  savedReports,
  savedReportsRelations,
  sessions,
  slas,
  slasRelations,
  taskAssignees,
  taskAssigneesRelations,
  taskDependencies,
  taskDependenciesRelations,
  // Tasks
  tasks,
  tasksRelations,
  taskTimeLogs,
  taskTimeLogsRelations,
  ticketAuditLogs,
  ticketAuditLogsRelations,
  ticketMacros,
  ticketMacrosRelations,
  ticketMessages,
  ticketMessagesRelations,
  // Support / tickets
  tickets,
  ticketsRelations,
  userActivityLogs,
  userActivityLogsRelations,
  userGroupMembers,
  userGroupMembersRelations,
  userGroups,
  userGroupsRelations,
  userInvitations,
  userInvitationsRelations,
  // Auth / users
  users,
  verificationTokens,
  webhookLogs,
  webhookLogsRelations,
  // Webhooks
  webhooks,
  webhooksRelations,
} from "./schema";
